// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjAjax.Models;

public partial class Address
{
    public int Id { get; set; }

    public string city { get; set; }

    public string site_id { get; set; }

    public string road { get; set; }
}